[uwsgi]
# Project directory
chdir           = /app
# Django's wsgi file
module          = know_more.wsgi:application
# The virtualenv (container python)
home            = /usr/local

# Process-related settings
master          = true
# Maximum number of worker processes
processes       = 4
# The socket (use the full path to be safe)
socket          = /app/know_more.sock
# ... with appropriate permissions - may be needed
chmod-socket    = 666
# Clear environment on exit
vacuum          = true

# Optimize
max-requests    = 5000
harakiri        = 20
post-buffering  = 8192

# Logging
logto           = /app/logs/uwsgi.log
