# Generated by Django 4.2.29 on 2026-04-05 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_tokens', models.IntegerField(default=50000, verbose_name='剩余可用 Tokens')),
                ('last_reset_date', models.DateField(default=django.utils.timezone.now, verbose_name='上次重置日期')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_token_usage', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户 Token 使用量',
                'verbose_name_plural': '用户 Token 使用量',
            },
        ),
    ]
