# Generated by Django 5.2.14 on 2026-06-19 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='机器人名称')),
                ('persona_prompt', models.TextField(verbose_name='人物设定提示词')),
                ('workflow_prompt', models.TextField(default='', verbose_name='工作流程提示词')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('weekly_action_count', models.IntegerField(default=3, verbose_name='每周行动次数')),
                ('total_posts', models.PositiveIntegerField(default=0, verbose_name='总发帖数')),
                ('total_replies', models.PositiveIntegerField(default=0, verbose_name='总回复数')),
                ('total_likes', models.PositiveIntegerField(default=0, verbose_name='总点赞数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_action_at', models.DateTimeField(blank=True, null=True, verbose_name='最后行动时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot_profile', to=settings.AUTH_USER_MODEL, verbose_name='绑定用户')),
            ],
            options={
                'verbose_name': '机器人档案',
                'verbose_name_plural': '机器人档案',
            },
        ),
        migrations.CreateModel(
            name='BotActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('post', '发帖'), ('reply', '回复'), ('like_post', '点赞帖子'), ('like_reply', '点赞回复'), ('favorite', '收藏'), ('read', '阅读')], max_length=20, verbose_name='行动类型')),
                ('target_id', models.IntegerField(blank=True, null=True, verbose_name='目标ID')),
                ('content_preview', models.TextField(blank=True, default='', verbose_name='内容预览')),
                ('ai_prompt_used', models.TextField(blank=True, default='', verbose_name='使用的提示词')),
                ('ai_response', models.TextField(blank=True, default='', verbose_name='AI响应')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('scheduled_at', models.DateTimeField(verbose_name='计划执行时间')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='实际执行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='ai.botprofile', verbose_name='机器人')),
            ],
            options={
                'verbose_name': '机器人行动日志',
                'verbose_name_plural': '机器人行动日志',
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['bot', '-scheduled_at'], name='ai_botactio_bot_id_fb2e57_idx'), models.Index(fields=['status'], name='ai_botactio_status_f8c235_idx')],
            },
        ),
    ]
